apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dns
  name: dns
spec:
  replicas: 3
  minReadySeconds: 60
  selector:
    matchLabels:
      run: dns
  template:
    metadata:
      labels:
        run: dns
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: run
                  operator: In
                  values:
                  - dns
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: gcr.io/google.com/bnjf-scratch/dns-echo
        name: dns-echo
        resources:
            requests:
              memory: "10M"
              cpu: "100m"
            limits:
              memory: "20M"
              cpu: "200m"
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: dns0
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 35.247.157.87
  selector:
    run: dns
  ports:
  - port: 53
    protocol: UDP
    targetPort: 5353
---
apiVersion: v1
kind: Service
metadata:
  name: dns1
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 35.247.134.30
  selector:
    run: dns
  ports:
  - port: 53
    protocol: UDP
    targetPort: 5353
---
